// File generated by flutterfire_cli or manually created
// This file contains Firebase configuration for all platforms

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // For web, you need to register a web app in Firebase Console
  // Go to Firebase Console > Project Settings > Your apps > Add app > Web
  // Then update the appId below with your web app ID
  // For now, using minimal config that should work
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy_e01_8f7Vz2lFHKYJRLv4N3oTrOFgX8',
    appId: '1:1031724299384:web:97fd97936d89e3515ee98d',
    messagingSenderId: '1031724299384',
    projectId: 'playsync-mad',
    authDomain: 'playsync-mad.firebaseapp.com',
    storageBucket: 'playsync-mad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_e01_8f7Vz2lFHKYJRLv4N3oTrOFgX8',
    appId: '1:1031724299384:android:97fd97936d89e3515ee98d',
    messagingSenderId: '1031724299384',
    projectId: 'playsync-mad',
    storageBucket: 'playsync-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_e01_8f7Vz2lFHKYJRLv4N3oTrOFgX8',
    appId: '1:1031724299384:ios:your-ios-app-id',
    messagingSenderId: '1031724299384',
    projectId: 'playsync-mad',
    storageBucket: 'playsync-mad.firebasestorage.app',
    iosBundleId: 'com.example.playsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy_e01_8f7Vz2lFHKYJRLv4N3oTrOFgX8',
    appId: '1:1031724299384:macos:your-macos-app-id',
    messagingSenderId: '1031724299384',
    projectId: 'playsync-mad',
    storageBucket: 'playsync-mad.firebasestorage.app',
    iosBundleId: 'com.example.playsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy_e01_8f7Vz2lFHKYJRLv4N3oTrOFgX8',
    appId: '1:1031724299384:windows:your-windows-app-id',
    messagingSenderId: '1031724299384',
    projectId: 'playsync-mad',
    storageBucket: 'playsync-mad.firebasestorage.app',
  );
}
